#!/bin/sh

docker run \
    --mount type=bind,src=$(pwd),target=/document \
    dive_into_data_science:latest \
    bash -c " \
    cd /document/book && \
    /home/runner/env/bin/python \
    /document/scripts/clear_notebook_outputs.py"

git add .
